// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Tue Oct 15 19:03:36 2024

contador4bits contador4bits_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.decrescente(decrescente_sig) ,	// input  decrescente_sig
	.resetar(resetar_sig) ,	// input  resetar_sig
	.max_value(max_value_sig) ,	// input [3:0] max_value_sig
	.reset(reset_sig) ,	// output  reset_sig
	.count(count_sig) 	// output [3:0] count_sig
);

